# Generated by Django 5.0.6 on 2024-06-21 22:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istok_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number_secondary',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('man', 'Мужской'), ('wom', 'Женский')], default=None, max_length=3, null=True, verbose_name='Ваш пол'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ren_planned',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], default=None, max_length=3, null=True, verbose_name='Планируется ли ремонт'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='has_children',
            field=models.CharField(choices=[('yes', 'Да'), ('no', 'Нет')], default=None, max_length=3, null=True, verbose_name='Наличие детей'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Номер телефона'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='renovation_plan',
            field=models.CharField(choices=[('already_ongoing', 'Уже идет'), ('starting_soon', 'Скоро приступаем'), ('within_half_year', 'В течение полугода'), ('within_year', 'В течение года')], default=None, max_length=100, null=True, verbose_name='Планируется ли ремонт?'),
        ),
        migrations.CreateModel(
            name='BonusProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bonus_points', models.DecimalField(decimal_places=2, max_digits=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateTimeField(default='2024-06-22 01:52:18.294602')),
                ('status', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
