# Generated by Django 5.0.6 on 2024-06-18 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istok_app', '0002_remove_userprofile_phone_number_secondary_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(blank=True, choices=[('kitchen', 'Кухня'), ('living-room', 'Гардероб'), ('bedroom', 'Прихожая'), ('dresser', 'Комод'), ('rack', 'Стеллаж')], max_length=100, null=True)),
                ('shape', models.CharField(blank=True, choices=[('straight', 'Прямой(ая)'), ('corner', 'Угловой(ая)'), ('p-shaped', 'П-образный(ая)'), ('l-shaped', 'Г-образный(ая)'), ('hidden', 'Скрытый(ая)')], max_length=100, null=True)),
                ('kitchen', models.CharField(blank=True, choices=[('bar-counter', 'С барной стойкой'), ('island', 'С островом')], max_length=100, null=True)),
                ('purpose', models.CharField(choices=[('house', 'Домой'), ('office', 'Офис'), ('child', 'детская')], max_length=100)),
                ('facade_material', models.CharField(blank=True, choices=[('LDSP', 'ЛДСП'), ('PVC', 'Пленка ПВХ'), ('AGT', 'Пластик AGT'), ('Fenix', 'Пластик Fenix'), ('Enamel', 'Эмаль')], max_length=100, null=True)),
                ('Table_top_material', models.CharField(blank=True, choices=[('HPL', 'Столешница ДСП с покрытием HPL'), ('Compact_laminate', 'Столешница компакт-ламинат'), ('Quartz', 'Кварцевые столешницы'), ('Acrylic', 'Акриловые столешницы')], max_length=100, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
