# Generated by Django 5.0.6 on 2024-05-31 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('istok_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='phone_number_secondary',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(max_length=15, unique=True, verbose_name='Номер телефона'),
        ),
    ]
